language: node_js
node_js:
- '8'
before_script:
- npm install grunt-cli -g
deploy:
  provider: heroku
  api_key:
    secure: jg9qZYJBTuhGX2tKTUz8nCyrPd7WYr6L1MCwAxtCCwjT9QCPQTHuCvUt85pDIpb1J9JdawItUhvPbcwyB3RDq4Dx0j6UK7MDEG+M67a8HMvcdgriTogX2n8kLIAkajlKNvT5ray4dUXlui8EFhoK59zOgiQ/SqxE9hPBD0slNcty3S+vpBLk0wlcG3k+VgnCkNeJYji3zilmHHYLvbDTsiDFFl6YInbqVADHHwrsUPN93mPQBGhkoDkeSIeCvR/HXsoiOi+EgxzXuAX04kMJUsAX7F/P47OvnAhL+MrxkvOwqlBKYoQfKVstjivDdW4kdG4fPn8fxFbdoPpRJh6uKV25f65JAyq3ZJVg6NAx/CwH1wo2O9/YR7EVAjagDdPl+0plb+oP9Lbp1d9hdAzkKUSzAtgE01nwMyUzHvCCmBdFLHQTujS/agfG/0oxYCkbiO0pTMX8kMRNNam5HfXUElOECWARiABQwSQf6BcrSsCghhPLM59y5VQ360MaFdz8ATczxDCZPs6d19mkKtzVaaZJ4+/4YqBvuYykRvqdco4hIYMO34E7jynqNPNqePaxPz+8fmzWM7ZpaaG3uKbdRMGJiyIM2f7Ux+jN9HcOuYy5da8ukKJBZ1YtpCthYjsCvRp6APVwuqQU+1zYIL/kHlM+h/kOu16m6IQow9w+ljc=
  app: findingfeynman
  on:
    repo: TomHodson/FindingFeynman
